name: Test pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dhgen:$(date +%s)
    - name: Run the tests
      run: docker run --rm -it dhgen:$(date +%s) python -m unittest tests/*.py
